"""add attachment sequence and description, survey screenshots_offered

Revision ID: 681abea3b826
Revises: 8eca5052dd18
Create Date: 2026-09-17 10:50:12.691189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681abea3b826'
down_revision: Union[str, Sequence[str], None] = '8eca5052dd18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('sequence_number', sa.SmallInteger(), nullable=False))
    op.add_column('attachments', sa.Column('description', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_attachments_survey_id_sequence_number', 'attachments', ['survey_id', 'sequence_number'])
    op.add_column('surveys', sa.Column('screenshots_offered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'screenshots_offered')
    op.drop_constraint('uq_attachments_survey_id_sequence_number', 'attachments', type_='unique')
    op.drop_column('attachments', 'description')
    op.drop_column('attachments', 'sequence_number')
    # ### end Alembic commands ###
