"""add metric observations and best experience platform

Revision ID: 8eca5052dd18
Revises: 8e3b7fa048bd
Create Date: 2026-09-17 10:32:49.818548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eca5052dd18'
down_revision: Union[str, Sequence[str], None] = '8e3b7fa048bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.SmallInteger(), nullable=True),
    sa.Column('metric_code', sa.Enum('TRIPS_PER_WEEK', 'TRIPS_PER_MONTH', 'ONLINE_HOURS_PER_WEEK', 'ONLINE_HOURS_PER_MONTH', 'WEEKLY_EARNINGS', 'MONTHLY_EARNINGS', 'ASP', 'TIPS', 'BONUS_SPEND', 'COMMISSION_PCT', 'DISTANCE_KM', name='metric_code'), nullable=False),
    sa.Column('source', sa.Enum('VERBAL', 'SCREENSHOT', 'INTERVIEWER_OBSERVATION', name='answer_source'), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], name=op.f('fk_metric_observations_attachment_id_attachments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_metric_observations_platform_id_platforms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_metric_observations_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_observations'))
    )
    op.create_index(op.f('ix_metric_observations_platform_id'), 'metric_observations', ['platform_id'], unique=False)
    op.create_index(op.f('ix_metric_observations_survey_id'), 'metric_observations', ['survey_id'], unique=False)
    op.create_index('uq_metric_obs_platform_scoped', 'metric_observations', ['survey_id', 'platform_id', 'metric_code', 'source'], unique=True, postgresql_where=sa.text('platform_id IS NOT NULL'))
    op.create_index('uq_metric_obs_survey_scoped', 'metric_observations', ['survey_id', 'metric_code', 'source'], unique=True, postgresql_where=sa.text('platform_id IS NULL'))
    op.add_column('surveys', sa.Column('best_experience_platform_id', sa.SmallInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_surveys_best_experience_platform_id_platforms'), 'surveys', 'platforms', ['best_experience_platform_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_surveys_best_experience_platform_id_platforms'), 'surveys', type_='foreignkey')
    op.drop_column('surveys', 'best_experience_platform_id')
    op.drop_index('uq_metric_obs_survey_scoped', table_name='metric_observations', postgresql_where=sa.text('platform_id IS NULL'))
    op.drop_index('uq_metric_obs_platform_scoped', table_name='metric_observations', postgresql_where=sa.text('platform_id IS NOT NULL'))
    op.drop_index(op.f('ix_metric_observations_survey_id'), table_name='metric_observations')
    op.drop_index(op.f('ix_metric_observations_platform_id'), table_name='metric_observations')
    op.drop_table('metric_observations')
    # ### end Alembic commands ###

    # autogenerate does not emit DROP TYPE for native Postgres enums.
    for enum_name in ("metric_code", "answer_source"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
