"""initial schema

Revision ID: c940fd1d2052
Revises: 
Create Date: 2026-09-17 09:55:38.869170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c940fd1d2052'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('code', name=op.f('uq_cities_code'))
    )
    op.create_table('driver_types',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver_types')),
    sa.UniqueConstraint('code', name=op.f('uq_driver_types_code'))
    )
    op.create_table('earnings_basis',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_earnings_basis')),
    sa.UniqueConstraint('code', name=op.f('uq_earnings_basis_code'))
    )
    op.create_table('interviewers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviewers')),
    sa.UniqueConstraint('telegram_user_id', name=op.f('uq_interviewers_telegram_user_id'))
    )
    op.create_table('payout_methods',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payout_methods')),
    sa.UniqueConstraint('code', name=op.f('uq_payout_methods_code'))
    )
    op.create_table('platforms',
    sa.Column('is_other', sa.Boolean(), nullable=False),
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platforms')),
    sa.UniqueConstraint('code', name=op.f('uq_platforms_code'))
    )
    op.create_table('ride_categories',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ride_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_ride_categories_code'))
    )
    op.create_table('switch_frequencies',
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_switch_frequencies')),
    sa.UniqueConstraint('code', name=op.f('uq_switch_frequencies_code'))
    )
    op.create_table('surveys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('human_code', sa.String(length=32), nullable=False),
    sa.Column('interviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.SmallInteger(), nullable=False),
    sa.Column('target_platform_id', sa.SmallInteger(), nullable=True),
    sa.Column('perceived_market_leader_platform_id', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='survey_status'), nullable=False),
    sa.Column('survey_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_weekly_earnings_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_weekly_earnings_currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name=op.f('ck_surveys_completed_after_started')),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_surveys_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['interviewers.id'], name=op.f('fk_surveys_interviewer_id_interviewers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['perceived_market_leader_platform_id'], ['platforms.id'], name=op.f('fk_surveys_perceived_market_leader_platform_id_platforms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_platform_id'], ['platforms.id'], name=op.f('fk_surveys_target_platform_id_platforms'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveys')),
    sa.UniqueConstraint('human_code', name=op.f('uq_surveys_human_code'))
    )
    op.create_index(op.f('ix_surveys_city_id'), 'surveys', ['city_id'], unique=False)
    op.create_index(op.f('ix_surveys_interviewer_id'), 'surveys', ['interviewer_id'], unique=False)
    op.create_index(op.f('ix_surveys_status'), 'surveys', ['status'], unique=False)
    op.create_index(op.f('ix_surveys_survey_datetime'), 'surveys', ['survey_datetime'], unique=False)
    op.create_index(op.f('ix_surveys_target_platform_id'), 'surveys', ['target_platform_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.SmallInteger(), nullable=True),
    sa.Column('telegram_file_id', sa.String(length=256), nullable=False),
    sa.Column('telegram_file_unique_id', sa.String(length=128), nullable=False),
    sa.Column('file_type', sa.Enum('SCREENSHOT', 'PHOTO', 'DOCUMENT', 'OTHER', name='attachment_file_type'), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('local_path', sa.String(length=512), nullable=True),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_attachments_platform_id_platforms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_attachments_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_index(op.f('ix_attachments_platform_id'), 'attachments', ['platform_id'], unique=False)
    op.create_index(op.f('ix_attachments_survey_id'), 'attachments', ['survey_id'], unique=False)
    op.create_table('driver_employment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('driver_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('fleet_name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_type_id'], ['driver_types.id'], name=op.f('fk_driver_employment_driver_type_id_driver_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_driver_employment_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver_employment')),
    sa.UniqueConstraint('survey_id', name=op.f('uq_driver_employment_survey_id'))
    )
    op.create_table('driver_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('internet_reliability', sa.Enum('POOR', 'FAIR', 'GOOD', 'EXCELLENT', 'UNKNOWN', name='internet_reliability'), nullable=True),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True),
    sa.Column('reason_to_join_new_platform', sa.Text(), nullable=True),
    sa.Column('seasonal_behavior_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_driver_experience_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver_experience')),
    sa.UniqueConstraint('survey_id', name=op.f('uq_driver_experience_survey_id'))
    )
    op.create_table('survey_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.SmallInteger(), nullable=False),
    sa.Column('platform_other_name', sa.String(length=128), nullable=True),
    sa.Column('works_with_platform', sa.Boolean(), nullable=False),
    sa.Column('is_exclusive', sa.Boolean(), nullable=True),
    sa.Column('switch_frequency_id', sa.SmallInteger(), nullable=True),
    sa.Column('experience_with_platform_months', sa.SmallInteger(), nullable=True),
    sa.Column('has_loyalty_program', sa.Boolean(), nullable=True),
    sa.Column('loyalty_program_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('experience_with_platform_months IS NULL OR experience_with_platform_months >= 0', name=op.f('ck_survey_platforms_experience_months_non_negative')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_survey_platforms_platform_id_platforms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_platforms_survey_id_surveys'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['switch_frequency_id'], ['switch_frequencies.id'], name=op.f('fk_survey_platforms_switch_frequency_id_switch_frequencies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_platforms')),
    sa.UniqueConstraint('survey_id', 'platform_id', name='uq_survey_platforms_survey_id_platform_id')
    )
    op.create_index(op.f('ix_survey_platforms_platform_id'), 'survey_platforms', ['platform_id'], unique=False)
    op.create_table('working_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('days_per_week', sa.SmallInteger(), nullable=True),
    sa.Column('hours_per_day', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('trips_per_day', sa.SmallInteger(), nullable=True),
    sa.Column('trips_per_week', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('days_per_week IS NULL OR days_per_week BETWEEN 0 AND 7', name=op.f('ck_working_stats_days_per_week_range')),
    sa.CheckConstraint('hours_per_day IS NULL OR hours_per_day BETWEEN 0 AND 24', name=op.f('ck_working_stats_hours_per_day_range')),
    sa.CheckConstraint('trips_per_day IS NULL OR trips_per_day >= 0', name=op.f('ck_working_stats_trips_per_day_non_negative')),
    sa.CheckConstraint('trips_per_week IS NULL OR trips_per_week >= 0', name=op.f('ck_working_stats_trips_per_week_non_negative')),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_working_stats_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_working_stats')),
    sa.UniqueConstraint('survey_id', name=op.f('uq_working_stats_survey_id'))
    )
    op.create_table('bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.SmallInteger(), nullable=False),
    sa.Column('receives_bonuses', sa.Boolean(), nullable=True),
    sa.Column('bonus_period', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'PER_TRIP', 'OTHER', name='bonus_period'), nullable=True),
    sa.Column('required_trips', sa.SmallInteger(), nullable=True),
    sa.Column('bonus_value_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bonus_value_currency', sa.String(length=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bonus_value_amount IS NULL OR bonus_value_amount >= 0', name=op.f('ck_bonuses_bonus_value_non_negative')),
    sa.CheckConstraint('required_trips IS NULL OR required_trips >= 0', name=op.f('ck_bonuses_required_trips_non_negative')),
    sa.ForeignKeyConstraint(['survey_id', 'platform_id'], ['survey_platforms.survey_id', 'survey_platforms.platform_id'], name='fk_bonuses_survey_platform', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bonuses')),
    sa.UniqueConstraint('survey_id', 'platform_id', name='uq_bonuses_survey_id_platform_id')
    )
    op.create_index(op.f('ix_bonuses_platform_id'), 'bonuses', ['platform_id'], unique=False)
    op.create_table('earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.SmallInteger(), nullable=False),
    sa.Column('weekly_earnings_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('weekly_earnings_currency', sa.String(length=3), nullable=True),
    sa.Column('earnings_basis_id', sa.SmallInteger(), nullable=True),
    sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('commission_pct IS NULL OR commission_pct BETWEEN 0 AND 100', name=op.f('ck_earnings_commission_pct_range')),
    sa.CheckConstraint('weekly_earnings_amount IS NULL OR weekly_earnings_amount >= 0', name=op.f('ck_earnings_weekly_earnings_non_negative')),
    sa.ForeignKeyConstraint(['earnings_basis_id'], ['earnings_basis.id'], name=op.f('fk_earnings_earnings_basis_id_earnings_basis'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_id', 'platform_id'], ['survey_platforms.survey_id', 'survey_platforms.platform_id'], name='fk_earnings_survey_platform', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_earnings')),
    sa.UniqueConstraint('survey_id', 'platform_id', name='uq_earnings_survey_id_platform_id')
    )
    op.create_index(op.f('ix_earnings_platform_id'), 'earnings', ['platform_id'], unique=False)
    op.create_table('market_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.SmallInteger(), nullable=False),
    sa.Column('estimated_driver_count', sa.Integer(), nullable=True),
    sa.Column('competitor_rider_discounts_notes', sa.Text(), nullable=True),
    sa.Column('demand_promotion_spending_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id', 'platform_id'], ['survey_platforms.survey_id', 'survey_platforms.platform_id'], name='fk_market_intelligence_survey_platform', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_intelligence')),
    sa.UniqueConstraint('survey_id', 'platform_id', name='uq_market_intelligence_survey_id_platform_id')
    )
    op.create_index(op.f('ix_market_intelligence_platform_id'), 'market_intelligence', ['platform_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.SmallInteger(), nullable=False),
    sa.Column('cash_pct', sa.SmallInteger(), nullable=True),
    sa.Column('digital_pct', sa.SmallInteger(), nullable=True),
    sa.Column('payout_method_id', sa.SmallInteger(), nullable=True),
    sa.Column('early_cashout_available', sa.Boolean(), nullable=True),
    sa.Column('cashout_fee_amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cashout_fee_is_percentage', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cash_pct IS NULL OR cash_pct BETWEEN 0 AND 100', name=op.f('ck_payments_cash_pct_range')),
    sa.CheckConstraint('cash_pct IS NULL OR digital_pct IS NULL OR cash_pct + digital_pct <= 100', name=op.f('ck_payments_cash_plus_digital_pct_at_most_100')),
    sa.CheckConstraint('cashout_fee_amount IS NULL OR cashout_fee_amount >= 0', name=op.f('ck_payments_cashout_fee_non_negative')),
    sa.CheckConstraint('digital_pct IS NULL OR digital_pct BETWEEN 0 AND 100', name=op.f('ck_payments_digital_pct_range')),
    sa.ForeignKeyConstraint(['payout_method_id'], ['payout_methods.id'], name=op.f('fk_payments_payout_method_id_payout_methods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_id', 'platform_id'], ['survey_platforms.survey_id', 'survey_platforms.platform_id'], name='fk_payments_survey_platform', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('survey_id', 'platform_id', name='uq_payments_survey_id_platform_id')
    )
    op.create_index(op.f('ix_payments_platform_id'), 'payments', ['platform_id'], unique=False)
    op.create_table('ride_category_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.SmallInteger(), nullable=False),
    sa.Column('category_id', sa.SmallInteger(), nullable=False),
    sa.Column('trip_share_pct', sa.SmallInteger(), nullable=True),
    sa.Column('is_main_category', sa.Boolean(), nullable=False),
    sa.Column('category_requirements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('trip_share_pct IS NULL OR trip_share_pct BETWEEN 0 AND 100', name=op.f('ck_ride_category_usages_trip_share_pct_range')),
    sa.ForeignKeyConstraint(['category_id'], ['ride_categories.id'], name=op.f('fk_ride_category_usages_category_id_ride_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_id', 'platform_id'], ['survey_platforms.survey_id', 'survey_platforms.platform_id'], name='fk_ride_category_usages_survey_platform', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ride_category_usages')),
    sa.UniqueConstraint('survey_id', 'platform_id', 'category_id', name='uq_ride_category_usages_survey_platform_category')
    )
    op.create_index(op.f('ix_ride_category_usages_category_id'), 'ride_category_usages', ['category_id'], unique=False)
    op.create_index(op.f('ix_ride_category_usages_platform_id'), 'ride_category_usages', ['platform_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_category_usages_platform_id'), table_name='ride_category_usages')
    op.drop_index(op.f('ix_ride_category_usages_category_id'), table_name='ride_category_usages')
    op.drop_table('ride_category_usages')
    op.drop_index(op.f('ix_payments_platform_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_market_intelligence_platform_id'), table_name='market_intelligence')
    op.drop_table('market_intelligence')
    op.drop_index(op.f('ix_earnings_platform_id'), table_name='earnings')
    op.drop_table('earnings')
    op.drop_index(op.f('ix_bonuses_platform_id'), table_name='bonuses')
    op.drop_table('bonuses')
    op.drop_table('working_stats')
    op.drop_index(op.f('ix_survey_platforms_platform_id'), table_name='survey_platforms')
    op.drop_table('survey_platforms')
    op.drop_table('driver_experience')
    op.drop_table('driver_employment')
    op.drop_index(op.f('ix_attachments_survey_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_platform_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_surveys_target_platform_id'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_survey_datetime'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_status'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_interviewer_id'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_city_id'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_table('switch_frequencies')
    op.drop_table('ride_categories')
    op.drop_table('platforms')
    op.drop_table('payout_methods')
    op.drop_table('interviewers')
    op.drop_table('earnings_basis')
    op.drop_table('driver_types')
    op.drop_table('cities')
    # ### end Alembic commands ###

    # autogenerate does not emit DROP TYPE for native Postgres enums since a
    # type can outlive the table that used it; here it can't, so clean them
    # up explicitly to make this migration actually reversible.
    for enum_name in ("survey_status", "attachment_file_type", "internet_reliability", "bonus_period"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
